name: Deploy Pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  HUGO_VERSION: "0.151.0" # https://github.com/google/docsy/blob/main/package.json
  DOCSY_VERSION: "v0.13.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: install hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i hugo.deb
          sudo snap install dart-sass
          npm install
      - name: npm install
        run: |
          cd themes/docsy/
          git fetch --tags
          git checkout tags/${DOCSY_VERSION}
          && npm install
      - run: hugo --minify
      - uses: actions/upload-pages-artifact@v4
        with:
          path: "./public"
      - uses: actions/deploy-pages@v4
        id: deployment
